project:
  type: website

website:
  title: "Poulami Sarker"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: EPPS 6323
        menu:
          - text: Assignment 1
            href: epps6323assignment1.qmd
          - text: Assignment 2
            href: epps6323assignment2.qmd
          - text: Assignment 3
            href: epps6323assignment3.qmd
      - text: Labs
        menu:
          - text: Lab 1
            href: Labs/Lab01.qmd
          - text: Lab 2
            href: Labs/Lab02.qmd
          - text: Lab 3
            href: Labs/Lab03.qmd
            
      - text: Reflections
        href: weeklyreflectionepps6323.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true